# DataFrame Merges

In [111]:
import pandas as pd
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],'data1': range(7)})

In [112]:
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],'data2': range(3)})

In [113]:
print df1
print df2

   data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b
   data2 key
0      0   a
1      1   b
2      2   d


In [4]:
pd.merge(df1, df2)#didn’t specify which column to join on. If not specified,  mergeuses the overlapping column names as the keys.

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [114]:
pd.merge(df1, df2, on='key')

data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      4   a      0
5      5   a      0

In [116]:
df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],'data1': range(7)})

In [117]:
df4 = pd.DataFrame({'rkey': ['a', 'b', 'd'],'data2': range(3)})

In [118]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey')

data1 lkey  data2 rkey
0      0    b      1    b
1      1    b      1    b
2      6    b      1    b
3      2    a      0    a
4      4    a      0    a
5      5    a      0    a

In [10]:

pd.merge(df1, df2, how='outer')

data1 key  data2
0    0.0   b    1.0
1    1.0   b    1.0
2    6.0   b    1.0
3    2.0   a    0.0
4    4.0   a    0.0
5    5.0   a    0.0
6    3.0   c    NaN
7    NaN   d    2.0

In [119]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],'data1': range(7)})

In [120]:
df2 = pd.DataFrame({'key': ['a', 'b', 'd','a'],'data2': range(4)})


In [124]:
print df1
print df2
pd.merge(df1, df2,how='inner')

   data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   a
6      6   b
   data2 key
0      0   a
1      1   b
2      2   d
3      3   a


data1 key  data2
0      0   b      1
1      1   b      1
2      6   b      1
3      2   a      0
4      2   a      3
5      4   a      0
6      4   a      3
7      5   a      0
8      5   a      3

In [125]:
left=pd.DataFrame({'key1': ['foo', 'foo', 'bar'],'key2': ['one', 'two', 'one'],'lval': [1, 2, 3]})
left

key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [126]:
right = pd.DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],'key2': ['one', 'one', 'one', 'two'], 'rval': [4, 5, 6, 7]})
right

key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [18]:
pd.merge(left, right, on=['key1', 'key2'], how='outer')

key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0

In [19]:
pd.merge(left, right, on='key1')

key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [20]:
pd.merge(left, right, on='key1', suffixes=('_left', '_right'))

key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

In [127]:
left1 = pd.DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'], 'value': range(6)})
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [128]:
right1 = pd.DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])

In [129]:
right1

group_val
a        3.5
b        7.0

In [25]:
pd.merge(left1, right1, left_on='key',right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [26]:
pd.merge(left1, right1, left_on='key', right_index=True, how='outer')

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [131]:
import numpy as np

In [133]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [33]:
lefth = pd.DataFrame({'key1': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],'key2': [2000, 2001, 2002, 2001, 2002],'data': np.arange(5.)})
lefth

data    key1  key2
0   0.0    Ohio  2000
1   1.0    Ohio  2001
2   2.0    Ohio  2002
3   3.0  Nevada  2001
4   4.0  Nevada  2002

In [39]:

righth = pd.DataFrame(np.arange(12).reshape((6, 2)),index=[['Nevada', 'Nevada', 'Ohio', 'Ohio', 'Ohio', 'Ohio'],
                                                        [2001, 2000, 2000, 2000, 2001, 2002]],columns=['event1', 'event2'])

In [40]:
righth

event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [41]:
pd.merge(lefth, righth, left_on=['key1', 'key2'], right_index=True)

data    key1  key2  event1  event2
0   0.0    Ohio  2000       4       5
0   0.0    Ohio  2000       6       7
1   1.0    Ohio  2001       8       9
2   2.0    Ohio  2002      10      11
3   3.0  Nevada  2001       0       1

In [134]:
pd.merge(lefth, righth, left_on=['key1', 'key2'],
 right_index=True, how='outer')

data    key1    key2  event1  event2
0   0.0    Ohio  2000.0     4.0     5.0
0   0.0    Ohio  2000.0     6.0     7.0
1   1.0    Ohio  2001.0     8.0     9.0
2   2.0    Ohio  2002.0    10.0    11.0
3   3.0  Nevada  2001.0     0.0     1.0
4   4.0  Nevada  2002.0     NaN     NaN
4   NaN  Nevada  2000.0     2.0     3.0

In [43]:
left2 = pd.DataFrame([[1., 2.], [3., 4.], [5., 6.]], index=['a', 'c', 'e'], columns=['Ohio', 'Nevada'])
left2

Ohio  Nevada
a   1.0     2.0
c   3.0     4.0
e   5.0     6.0

In [44]:
right2 = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [13, 14]], index=['b', 'c', 'd', 'e'], columns=['Missouri', 'Alabama'])
right2

Missouri  Alabama
b       7.0      8.0
c       9.0     10.0
d      11.0     12.0
e      13.0     14.0

In [135]:
pd.merge(left2, right2, how='outer', left_index=True, right_index=True)

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [136]:
left2.join(right2, how='outer')

Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
b   NaN     NaN       7.0      8.0
c   3.0     4.0       9.0     10.0
d   NaN     NaN      11.0     12.0
e   5.0     6.0      13.0     14.0

In [137]:
print left1
print right1
left1.join(right1, on='key')


  key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5
   group_val
a        3.5
b        7.0


key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

In [139]:

another = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [16., 17.]],index=['a', 'c', 'e', 'f'], columns=['New York', 'Oregon'])

In [140]:
print left2
print right2

   Ohio  Nevada
a   1.0     2.0
c   3.0     4.0
e   5.0     6.0
   Missouri  Alabama
b       7.0      8.0
c       9.0     10.0
d      11.0     12.0
e      13.0     14.0


In [141]:
right2.join([left2, another])

Missouri  Alabama  Ohio  Nevada  New York  Oregon
b       7.0      8.0   NaN     NaN       NaN     NaN
c       9.0     10.0   3.0     4.0       9.0    10.0
d      11.0     12.0   NaN     NaN       NaN     NaN
e      13.0     14.0   5.0     6.0      11.0    12.0

In [142]:
left2.join([right2, another], how='outer')


Ohio  Nevada  Missouri  Alabama  New York  Oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
b   NaN     NaN       7.0      8.0       NaN     NaN
c   3.0     4.0       9.0     10.0       9.0    10.0
d   NaN     NaN      11.0     12.0       NaN     NaN
e   5.0     6.0      13.0     14.0      11.0    12.0
f   NaN     NaN       NaN      NaN      16.0    17.0

# Concatenating Along an Axis

In [144]:
 arr = np.arange(12).reshape((3, 4))
print arr
print "------------"
ar1=np.array([[ 0, 1, 2,7],
[ 4, 5, 6,8],
[ 8, 9, 10,8]])
np.concatenate([arr, ar1], axis=1)




[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
------------


array([[ 0,  1,  2,  3,  0,  1,  2,  7],
       [ 4,  5,  6,  7,  4,  5,  6,  8],
       [ 8,  9, 10, 11,  8,  9, 10,  8]])

In [146]:
s1 = pd.Series([0, 1], index=['a', 'b'])
print s1
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = pd.Series([5, 6], index=['f', 'g'])
pd.concat([s1, s2, s3])

a    0
b    1
dtype: int64


a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [147]:
pd.concat([s1, s2, s3], axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [148]:
s4 = pd.concat([s1 * 5, s3])
s4

a    0
b    5
f    5
g    6
dtype: int64

In [149]:
pd.concat([s1, s4], axis=1)

0  1
a  0.0  0
b  1.0  5
f  NaN  5
g  NaN  6

In [150]:
pd.concat([s1, s4], axis=1, join='inner')

0  1
a  0  0
b  1  5

In [151]:
pd.concat([s1, s4], axis=1, join_axes=[['a', 'c', 'b', 'e']])

0    1
a  0.0  0.0
c  NaN  NaN
b  1.0  5.0
e  NaN  NaN

In [68]:
pd.concat([s1, s4], axis=1, join_axes=[['a', 'c', 'b', 'e']])

0    1
a  0.0  0.0
c  NaN  NaN
b  1.0  5.0
e  NaN  NaN

In [152]:
result = pd.concat([s1, s1, s3], keys=['one', 'two', 'three'])
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [153]:
result.unstack()

a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  NaN  NaN  5.0  6.0

In [75]:
pd.concat([s1, s2, s3], axis=1, keys=['one', 'two', 'three'])

one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [155]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2),\
                   index=['a', 'b', 'c'], columns=['one', 'two'])

df1

one  two
a    0    1
b    2    3
c    4    5

In [156]:
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=['a', 'c'],columns=['three', 'four'])

In [157]:
df2

three  four
a      5     6
c      7     8

In [159]:
pd.concat({'level1': df1, 'level2': df2}, axis=1)

level1     level2     
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [160]:
pd.concat([df1, df2], axis=1, keys=['level1', 'level2'], names=['upper', 'lower'])

upper level1     level2     
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [161]:
print df1
print df2

   one  two
a    0    1
b    2    3
c    4    5
   three  four
a      5     6
c      7     8


In [162]:
df1 = pd.DataFrame(np.random.randn(3, 4), columns=['a', 'b', 'c', 'd'])
df1

a         b         c         d
0  0.009273  1.866731  1.550339 -0.482845
1  0.405251  0.436883  0.729567  0.569374
2  0.967710  0.058506 -0.801785  0.809518

In [163]:
df2 = pd.DataFrame(np.random.randn(2, 3), columns=['b', 'd', 'a'])
df2

b         d         a
0  0.601547 -1.046693  1.506737
1 -1.223312 -0.170697  0.267613

In [167]:
 pd.concat([df1, df2],ignore_index=True)

a         b         c         d
0  0.009273  1.866731  1.550339 -0.482845
1  0.405251  0.436883  0.729567  0.569374
2  0.967710  0.058506 -0.801785  0.809518
3  1.506737  0.601547       NaN -1.046693
4  0.267613 -1.223312       NaN -0.170697

In [168]:
pd.concat([df1, df2], axis=1, keys=['level1', 'level2'], names=['upper', 'lower'])

upper    level1                                  level2                    
lower         a         b         c         d         b         d         a
0      0.009273  1.866731  1.550339 -0.482845  0.601547 -1.046693  1.506737
1      0.405251  0.436883  0.729567  0.569374 -1.223312 -0.170697  0.267613
2      0.967710  0.058506 -0.801785  0.809518       NaN       NaN       NaN

In [97]:
df1 = pd.DataFrame(np.random.randn(3, 4), columns=['a', 'b', 'c', 'd'])

In [98]:
df2 = pd.DataFrame(np.random.randn(2, 3), columns=['b', 'd', 'a'])

In [99]:
pd.concat([df1, df2], ignore_index=True)


a         b         c         d
0  0.618118 -1.364165 -2.706337  0.171010
1  1.376757 -1.895356 -0.961159  0.896362
2  0.808497 -0.362651  0.192841 -0.221375
3  0.112995 -1.090307       NaN -0.408461
4 -0.197155 -1.129528       NaN -0.255235

In [169]:
a = pd.Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],index=['f', 'e', 'd', 'c', 'b', 'a'])

In [170]:
b = pd.Series(np.arange(len(a), dtype=np.float64),index=['f', 'e', 'd', 'c', 'b', 'a'])

In [171]:
print a
print b

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64
f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    5.0
dtype: float64


In [174]:
b[-1] = np.nan

In [175]:
anew=np.where(pd.isnull(a), b, a)
print anew

[ 0.   2.5  2.   3.5  4.5  nan]


In [176]:
b.combine_first(a)

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [80]:
df1 = pd.DataFrame({'a': [1., np.nan, 5., np.nan],
 'b': [np.nan, 2., np.nan, 6.],
'c': range(2, 18, 4)})

In [82]:
df2 =pd. DataFrame({'a': [5., 4., np.nan, 3., 7.],
 'b': [np.nan, 3., 4., 6., 8.]})

In [83]:
df1.combine_first(df2)

a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

In [85]:
data = pd.DataFrame(np.arange(6).reshape((2, 3)),
index=pd.Index(['Ohio', 'Colorado'], name='state'),
 columns=pd.Index(['one', 'two', 'three'], name='number'))

In [86]:
result = data.stack()

In [87]:
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32

In [4]:

import numpy as np
data = pd.DataFrame(np.arange(6).reshape((2, 3)), index=pd.Index(['Ohio', 'Colorado'], name='state'),
                columns=pd.Index(['one', 'two', 'three'], name='number'))

In [5]:
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [20]:
result = data.stack()

In [7]:
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32

In [8]:
result.unstack()

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [24]:
result.unstack('number')

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [22]:
result = data.stack()

In [25]:
s1 = pd.Series([0, 1, 2, 3], index=['a', 'b', 'c', 'd'])

In [28]:
s2 = pd.Series([4, 5, 6], index=['c', 'd', 'e'])
print s1
print s2

a    0
b    1
c    2
d    3
dtype: int64
c    4
d    5
e    6
dtype: int64


In [29]:
data2 = pd.concat([s1, s2], keys=['one', 'two'])
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: int64

In [33]:
res=data2.unstack()


In [32]:
res.stack()

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
two  c    4.0
     d    5.0
     e    6.0
dtype: float64

In [40]:
df = pd.DataFrame({'left': result, 'right': result + 5},
 columns=pd.Index(['left', 'right'], name='side'))
df

side             left  right
state    number             
Ohio     one        0      5
         two        1      6
         three      2      7
Colorado one        3      8
         two        4      9
         three      5     10

In [43]:
df.unstack(1)

side     left           right          
number    one two three   one two three
state                                  
Ohio        0   1     2     5   6     7
Colorado    3   4     5     8   9    10

In [44]:
df.unstack('state').stack('side')

state         Ohio  Colorado
number side                 
one    left      0         3
       right     5         8
two    left      1         4
       right     6         9
three  left      2         5
       right     7        10

In [61]:
import csv
with open('StudentReg.csv','r') as f:
    rows = csv.reader(f)
    ldata=pd.DataFrame(rows)

TypeError: data argument can't be an iterator

In [2]:
import  pandas as pd

df = pd.read_csv("StudentReg.csv")
print(df)

    Registration Number  Batch                          Remarks  \
0       RA1411008010001      1                              NaN   
1       RA1411008010002      1                              NaN   
2       RA1411008010004      1                              NaN   
3       RA1411008010005      1                              NaN   
4       RA1411008010006      2                              NaN   
5       RA1411008010007      2                              NaN   
6       RA1411008010008      2                              NaN   
7       RA1411008010009      1                              NaN   
8       RA1411008010010      1                              NaN   
9       RA1411008010011      1                              NaN   
10      RA1411008010012      1                              NaN   
11      RA1411008010013      1                              NaN   
12      RA1411008010014      1                              NaN   
13      RA1411008010015      1                              Na

In [63]:
pivoted = df.pivot('Registration Number', 'Course Code', 'Faculty ID - Name')

In [64]:
pivoted

Course Code          BM1201  -  Introduction to Biomedical Devices  \
Registration Number                                                  
RA1411008010001                                               None   
RA1411008010002                                               None   
RA1411008010004                                               None   
RA1411008010005                                               None   
RA1411008010006                                               None   
RA1411008010007                                               None   
RA1411008010008                                               None   
RA1411008010009                                               None   
RA1411008010010                                               None   
RA1411008010011                                               None   
RA1411008010012                                               None   
RA1411008010013                                               None   
RA1411008010014                                               None   
RA1411008010015                                               None   
RA1411008010016                                               None   
RA1411008010017                                               None   
RA1411008010018      100040 - Dr.T.Jayanthi - Slot : G - Batch : 1   
RA1411008010019                                               None   
RA1411008010020                                               None   
RA1411008010021                                               None   
RA1411008010022                                               None   
RA1411008010023                                               None   
RA1411008010024                                               None   
RA1411008010025                                               None   
RA1411008010026                                               None   
RA1411008010027                                               None   
RA1411008010028                                               None   
RA1411008010029                                               None   
RA1411008010030                                               None   
RA1411008010031                                               None   
...                                                            ...   
RA1411008010324                                               None   
RA1411008010325                                               None   
RA1411008010326                                               None   
RA1411008010327                                               None   
RA1411008010328                                               None   
RA1411008010329                                               None   
RA1411008010331                                               None   
RA1411008010332                                               None   
RA1411008010333                                               None   
RA1411008010334                                               None   
RA1411008010336                                               None   
RA1411008010339                                               None   
RA1411008010341                                               None   
RA1411008010342                                               None   
RA1411008010343                                               None   
RA1411008010344                                               None   
RA1411008010345                                               None   
RA1411008010346                                               None   
RA1411008010347                                               None   
RA1411008010348                                               None   
RA1411008010349                                               None   
RA1411008010350                                               None   
RA1411008010353      100040 - Dr.T.Jayanthi - Slot : G - Batch : 1   
RA1411008010356                                               None   
RA14110080

In [65]:
pivoted.head()

Course Code         BM1201  -  Introduction to Biomedical Devices  \
Registration Number                                                 
RA1411008010001                                              None   
RA1411008010002                                              None   
RA1411008010004                                              None   
RA1411008010005                                              None   
RA1411008010006                                              None   

Course Code         CE1205  -  Global Warming and Climate Change  \
Registration Number                                                
RA1411008010001                                             None   
RA1411008010002                                             None   
RA1411008010004                                             None   
RA1411008010005                                             None   
RA1411008010006                                             None   

Course Code         CE1206  -  Disaster Management and Mitigation  \
Registration Number                                                 
RA1411008010001                                              None   
RA1411008010002                                              None   
RA1411008010004                                              None   
RA1411008010005                                              None   
RA1411008010006                                              None   

Course Code         CY1202  -  Advanced Analytical Methods  \
Registration Number                                          
RA1411008010001                                       None   
RA1411008010002                                       None   
RA1411008010004                                       None   
RA1411008010005                                       None   
RA1411008010006                                       None   

Course Code         EE1203  -  Renewable Energy Resources  \
Registration Number                                         
RA1411008010001                                      None   
RA1411008010002                                      None   
RA1411008010004                                      None   
RA1411008010005                                      None   
RA1411008010006                                      None   

Course Code         EE1204  -  Soft Computing  \
Registration Number                             
RA1411008010001                          None   
RA1411008010002                          None   
RA1411008010004                          None   
RA1411008010005                          None   
RA1411008010006                          None   

Course Code         FP1203  -  Technology of Bakery and Confectionery Products  \
Registration Number                                                              
RA1411008010001                                                   None           
RA1411008010002                                                   None           
RA1411008010004                                                   None           
RA1411008010005                                                   None           
RA1411008010006                                                   None           

Course Code         FP1205  -  Food Processing and Preservation Technology  \
Registration Number                                                          
RA1411008010001                                                   None       
RA1411008010002                                                   None       
RA1411008010004                                                   None       
RA1411008010005                                                   None       
RA1411008010006                                                   None       

Course Code         GN1203  -  DAY TO DAY BIOLOGY  \
Registration Number                                 
RA1411008010001                              None   
RA1411008010002                              None   
RA141100801000

In [66]:
pivoted = df.pivot('Registration Number', 'Course Code')

In [68]:
pivoted.head()

Batch  \
Course Code         BM1201  -  Introduction to Biomedical Devices   
Registration Number                                                 
RA1411008010001                                               NaN   
RA1411008010002                                               NaN   
RA1411008010004                                               NaN   
RA1411008010005                                               NaN   
RA1411008010006                                               NaN   

                                                                  \
Course Code         CE1205  -  Global Warming and Climate Change   
Registration Number                                                
RA1411008010001                                              NaN   
RA1411008010002                                              NaN   
RA1411008010004                                              NaN   
RA1411008010005                                              NaN   
RA1411008010006                                              NaN   

                                                                   \
Course Code         CE1206  -  Disaster Management and Mitigation   
Registration Number                                                 
RA1411008010001                                               NaN   
RA1411008010002                                               NaN   
RA1411008010004                                               NaN   
RA1411008010005                                               NaN   
RA1411008010006                                               NaN   

                                                            \
Course Code         CY1202  -  Advanced Analytical Methods   
Registration Number                                          
RA1411008010001                                        NaN   
RA1411008010002                                        NaN   
RA1411008010004                                        NaN   
RA1411008010005                                        NaN   
RA1411008010006                                        NaN   

                                                           \
Course Code         EE1203  -  Renewable Energy Resources   
Registration Number                                         
RA1411008010001                                       NaN   
RA1411008010002                                       NaN   
RA1411008010004                                       NaN   
RA1411008010005                                       NaN   
RA1411008010006                                       NaN   

                                               \
Course Code         EE1204  -  Soft Computing   
Registration Number                             
RA1411008010001                           NaN   
RA1411008010002                           NaN   
RA1411008010004                           NaN   
RA1411008010005                           NaN   
RA1411008010006                           NaN   

                                                                                \
Course Code         FP1203  -  Technology of Bakery and Confectionery Products   
Registration Number                                                              
RA1411008010001                                                    NaN           
RA1411008010002                                                    NaN           
RA1411008010004                                                    NaN           
RA1411008010005                                                    NaN           
RA1411008010006                                                    NaN           

                                                                            \
Course Code         FP1205  -  Food Processing and Preservation Technology   
Registration Number                                                          
RA1411008010001                                                    NaN       
RA1411008010002                                              

In [69]:
pivoted.to_csv('Coursecode.csv')

In [74]:
data = pd.DataFrame({'k1': ['one'] * 3 + ['two'] * 4, 'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [75]:
data.duplicated()


0    False
1     True
2    False
3    False
4     True
5    False
6     True
dtype: bool

In [76]:
data.drop_duplicates()

k1  k2
0  one   1
2  one   2
3  two   3
5  two   4

In [80]:
data['v1'] = range(7)
print data

    k1  k2  v1
0  one   1   0
1  one   1   1
2  one   2   2
3  two   3   3
4  two   3   4
5  two   4   5
6  two   4   6


In [82]:
data.drop_duplicates(['v1'])


k1  k2  v1
0  one   1   0
1  one   1   1
2  one   2   2
3  two   3   3
4  two   3   4
5  two   4   5
6  two   4   6

In [84]:
data =pd. DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami',
 'corned beef', 'Bacon', 'pastrami', 'honey ham',
 'nova lox'],

                  'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [85]:
meat_to_animal = {
'bacon': 'pig',
'pulled pork': 'pig',
'pastrami': 'cow',
'corned beef': 'cow',
'honey ham': 'pig',
'nova lox': 'salmon'
}

In [86]:
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)

In [87]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [89]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [5]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [93]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [94]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [95]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [96]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

# Renaming Axis Indexes

In [98]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
 index=['Ohio', 'Colorado', 'New York'],
columns=['one', 'two', 'three', 'four'])

In [99]:
data.index.map(str.upper)

array(['OHIO', 'COLORADO', 'NEW YORK'], dtype=object)

In [100]:
data.index = data.index.map(str.upper)
data

In [101]:
data.rename(index=str.title, columns=str.upper)

one  two  three  four
OHIO        0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

In [102]:
data.rename(index={'OHIO': 'INDIANA'},
 columns={'three': 'peekaboo'})


one  two  peekaboo  four
INDIANA     0    1         2     3
COLORADO    4    5         6     7
NEW YORK    8    9        10    11

In [104]:
_ = data.rename(index={'OHIO': 'INDIANA'}, inplace=True)

In [105]:
data

one  two  three  four
INDIANA     0    1      2     3
COLORADO    4    5      6     7
NEW YORK    8    9     10    11

# Discretization and Binning

In [111]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
print cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, object): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]


In [108]:
cats.codes#labels

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [109]:
cats.levels

C:\Program Files\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: Accessing 'levels' is deprecated, use 'categories'
  if __name__ == '__main__':


Index([u'(18, 25]', u'(25, 35]', u'(35, 60]', u'(60, 100]'], dtype='object')

In [110]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [112]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)


[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, object): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [113]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [115]:
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [122]:
data = np.random.rand(20)
x=pd.cut(data, 4, precision=2)
pd.value_counts(x)

(0.29, 0.53]     7
(0.76, 1]        5
(0.53, 0.76]     4
(0.055, 0.29]    4
dtype: int64

In [119]:
data = np.random.randn(1000) # Normally distributed
cats = pd.qcut(data, 4) # Cut into quartiles
cats

[(-0.00252, 0.641], (0.641, 2.751], (-0.655, -0.00252], (-0.655, -0.00252], [-2.739, -0.655], ..., (-0.00252, 0.641], (-0.00252, 0.641], (-0.00252, 0.641], (-0.655, -0.00252], (0.641, 2.751]]
Length: 1000
Categories (4, object): [[-2.739, -0.655] < (-0.655, -0.00252] < (-0.00252, 0.641] < (0.641, 2.751]]

In [120]:
pd.value_counts(cats)

(0.641, 2.751]        250
(-0.00252, 0.641]     250
(-0.655, -0.00252]    250
[-2.739, -0.655]      250
dtype: int64

In [123]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(0.219, 0.486], (0.486, 0.964], (0.219, 0.486], (0.219, 0.486], [0.0564, 0.219], ..., (0.964, 0.999], (0.964, 0.999], [0.0564, 0.219], (0.486, 0.964], (0.219, 0.486]]
Length: 20
Categories (4, object): [[0.0564, 0.219] < (0.219, 0.486] < (0.486, 0.964] < (0.964, 0.999]]

# Detecting and Filtering Outliers

In [126]:
np.random.seed(12345)
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528

In [134]:
col = data[3]
col[np.abs(col) > 3]


97     3.927528
305   -3.399312
400   -3.745356
Name: 3, dtype: float64

In [135]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
5   -0.539741  0.476985  3.248944 -1.021228
97  -0.774363  0.552936  0.106061  3.927528
102 -0.655054 -0.565230  3.176873  0.959533
305 -2.315555  0.457246 -0.025907 -3.399312
324  0.050188  1.951312  3.260383  0.963301
400  0.146326  0.508391 -0.196713 -3.745356
499 -0.293333 -0.242459 -3.056990  1.918403
523 -3.428254 -0.296336 -0.439938 -0.867165
586  0.275144  1.179227 -3.184377  1.369891
808 -0.362528 -3.548824  1.553205 -2.186301
900  3.366626 -2.372214  0.851010  1.332846

In [138]:
data[np.abs(data) > 3]=np.sign(data) * 3

SyntaxError: invalid syntax (<ipython-input-138-2e593bca3fbf>, line 1)

In [141]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067623     0.068473     0.025153    -0.002081
std       0.995485     0.990253     1.003977     0.989736
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.000000     2.653656     3.000000     3.000000

# Permutation and Random Sampling

In [145]:
df = pd.DataFrame(np.arange(5 * 4).reshape(5, 4))
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [146]:
sampler = np.random.permutation(5)

In [147]:
sampler

array([1, 3, 4, 0, 2])

In [149]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
3  12  13  14  15
4  16  17  18  19
0   0   1   2   3
2   8   9  10  11

In [151]:
df.take(np.random.permutation(len(df))[:3])

0   1   2   3
1   4   5   6   7
0   0   1   2   3
4  16  17  18  19

In [3]:
bag = np.array([5, 7, -1, 6, 4])

In [11]:
import numpy as np
sampler = np.random.randint(0, len(bag), size=10)
sampler

array([2, 1, 3, 3, 2, 0, 2, 1, 4, 2])

In [12]:
draws = bag.take(sampler)

In [13]:
draws

array([-1,  7,  6,  6, -1,  5, -1,  7,  4, -1])

# Computing Indicator/Dummy Variables

In [17]:

import pandas as pd
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
'data1': range(6)})
df

data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   b

In [18]:
pd.get_dummies(df['key'])

a    b    c
0  0.0  1.0  0.0
1  0.0  1.0  0.0
2  1.0  0.0  0.0
3  0.0  0.0  1.0
4  1.0  0.0  0.0
5  0.0  1.0  0.0

In [20]:
dummies = pd.get_dummies(df['key'], prefix='key')
dummies

key_a  key_b  key_c
0    0.0    1.0    0.0
1    0.0    1.0    0.0
2    1.0    0.0    0.0
3    0.0    0.0    1.0
4    1.0    0.0    0.0
5    0.0    1.0    0.0

In [21]:
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0    0.0    1.0    0.0
1      1    0.0    1.0    0.0
2      2    1.0    0.0    0.0
3      3    0.0    0.0    1.0
4      4    1.0    0.0    0.0
5      5    0.0    1.0    0.0

# String Manipulation

# refer string and regular expression notebook

In [22]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com',
 'Rob': 'rob@gmail.com', 'Wes': np.nan}

In [25]:
data = pd.Series(data)
data

Dave     dave@google.com
Rob        rob@gmail.com
Steve    steve@gmail.com
Wes                  NaN
dtype: object

In [26]:
data.isnull()

Dave     False
Rob      False
Steve    False
Wes       True
dtype: bool

In [27]:
data.str.contains('gmail')

Dave     False
Rob       True
Steve     True
Wes        NaN
dtype: object

In [30]:
import re
pattern='([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [31]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Rob        [(rob, gmail, com)]
Steve    [(steve, gmail, com)]
Wes                        NaN
dtype: object

In [32]:
matches = data.str.match(pattern, flags=re.IGNORECASE)

C:\Program Files\Anaconda2\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: In future versions of pandas, match will change to always return a bool indexer.
  if __name__ == '__main__':


In [33]:
matches

Dave     (dave, google, com)
Rob        (rob, gmail, com)
Steve    (steve, gmail, com)
Wes                      NaN
dtype: object

In [34]:
 matches.str.get(1)

Dave     google
Rob       gmail
Steve     gmail
Wes         NaN
dtype: object

In [35]:
matches.str[0]

Dave      dave
Rob        rob
Steve    steve
Wes        NaN
dtype: object

In [36]:
data.str[:5]

Dave     dave@
Rob      rob@g
Steve    steve
Wes        NaN
dtype: object

# JSON: to be done